openapi: 3.0.0
info:
  title: Still Awake • Creator Assistant API
  description: |
    API hỗ trợ cho kênh "Still Awake • with Lana", bao gồm các hành động tạo tiêu đề, mô tả, hashtag, prompt cho ảnh, nhạc, video, caption, metadata, v.v.
  version: "1.0.0"
  contact:
    name: Lana
    url: https://stillawakewithlana.com

paths:
  /generate_title:
    post:
      summary: Tạo tiêu đề chuẩn SEO cho YouTube
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TitleInput"
      responses:
        '200':
          description: Kết quả tiêu đề
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TitleOutput"

  /generate_description:
    post:
      summary: Viết mô tả có biểu tượng và hashtag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DescriptionInput"
      responses:
        '200':
          description: Mô tả hoàn chỉnh
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescriptionOutput"

  /generate_comment_cta:
    post:
      summary: Tạo bình luận gợi call-to-action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentInput"
      responses:
        '200':
          description: Bình luận CTA
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommentOutput"

  /generate_thumbnail_prompt:
    post:
      summary: Tạo prompt cho thumbnail video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ThumbnailInput"
      responses:
        '200':
          description: Prompt thumbnail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ThumbnailOutput"

  /generate_video_prompt:
    post:
      summary: Tạo prompt cho video cinematic (Dreamina, Veo3)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VideoPromptInput"
      responses:
        '200':
          description: Prompt video
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VideoPromptOutput"

  /generate_suno_prompt:
    post:
      summary: Tạo prompt nhạc Suno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SunoPromptInput"
      responses:
        '200':
          description: Prompt nhạc
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SunoPromptOutput"

  /generate_facebook_caption:
    post:
      summary: Caption cho Facebook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FacebookInput"
      responses:
        '200':
          description: Caption
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FacebookOutput"

  /generate_instagram_caption:
    post:
      summary: Caption cho Instagram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InstagramInput"
      responses:
        '200':
          description: Caption
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstagramOutput"

  /generate_reel_caption:
    post:
      summary: Caption cho video reel ngắn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReelInput"
      responses:
        '200':
          description: Caption reel
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReelOutput"

  /generate_multi_platform_caption:
    post:
      summary: Caption đồng bộ đa nền tảng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MultiPlatformInput"
      responses:
        '200':
          description: Caption đa nền tảng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MultiPlatformOutput"

  /generate_keywords:
    post:
      summary: Gợi ý từ khóa SEO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeywordsInput"
      responses:
        '200':
          description: Danh sách từ khóa
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeywordsOutput"

  /generate_metadata:
    post:
      summary: Tạo metadata video/audio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MetadataInput"
      responses:
        '200':
          description: Metadata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetadataOutput"

  /generate_hashtags:
    post:
      summary: Gợi ý hashtag cho nội dung
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HashtagInput"
      responses:
        '200':
          description: Hashtag
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HashtagOutput"

  /generate_playlist_structure:
    post:
      summary: Cấu trúc playlist nhạc dài
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaylistInput"
      responses:
        '200':
          description: Cấu trúc playlist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaylistOutput"

  /generate_podcast_description:
    post:
      summary: Viết mô tả podcast nhẹ nhàng, chuẩn SEO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PodcastInput"
      responses:
        '200':
          description: Mô tả podcast
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PodcastOutput"

  /generate_brand_voice:
    post:
      summary: Định nghĩa brand voice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BrandVoiceInput"
      responses:
        '200':
          description: Brand voice
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BrandVoiceOutput"

  /spotify_upload_helper:
    post:
      summary: Hướng dẫn đăng sản phẩm lên Spotify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpotifyInput"
      responses:
        '200':
          description: Hướng dẫn Spotify
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpotifyOutput"

components:
  schemas:
    TitleInput:
      type: object
      properties:
        topic:
          type: string
    TitleOutput:
      type: object
      properties:
        title:
          type: string